name: Build
on:
  push: { branches: ["**"] }
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle
      - uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.8
          arguments: build --no-daemon
      - uses: actions/upload-artifact@v4
        with:
          name: trinkets-sync-bridge-mysql-v2
          path: |
            build/libs/*.jar
            !build/libs/*-sources.jar
            !build/libs/*-javadoc.jar
