name: Build
on: { push: { branches: ["**"] } }
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.8
          arguments: build --no-daemon
      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: trinkets-sync-bridge-mysql
          path: build/libs/*.jar
